# Generated by Django 5.1.4 on 2025-01-12 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("SCHEDULED", "Review Scheduled"),
                            ("FEEDBACK", "Feedback Provided"),
                            ("APPROVAL", "Under Approval"),
                            ("APPROVED", "Review Approved"),
                            ("REJECTED", "Review Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
